ALTER TABLE users RENAME COLUMN username TO email;
ALTER TABLE users ADD COLUMN username VARCHAR(125);
ALTER TABLE users ADD COLUMN first_name VARCHAR(30);
ALTER TABLE users ADD COLUMN last_name VARCHAR(30);